name: Integration Tests

on: [push]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r required_libraries.txt

      - name: Run integration tests
        run: |
          python run_integration_tests.py
