name: Validate on Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  validate-packer:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Message
        run: echo "Pull request has been opened from a forked repository to the organization's repository."

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
            version: "latest"

      - name: Packer init
        run: |
              packer init packer/packer-ami.pkr.hcl

      - name: Validate Packer Template
        run: |
          packer validate ami.debian-packer-aws.pkr.hcl

      - name: Check Formatting
        run: |
          if ! packer fmt -check=true ami.debian-packer-aws.pkr.hcl; then
            echo "Packer template is not formatted correctly. Please format it using 'packer fmt' and commit the changes."
            exit 1
          fi
